name: C/C++ CI

on: [push]

jobs:
  build:
    env:
      CONDA_USER_ID: 9001
      CONDA_USER: conda
      CONDA_GROUP_ID: 32001
      CONDA_INSTALL_DIR: /opt/conda
      CONDA_HOME: /home/conda
      CONDA_BLD_PATH: /home/conda/artefacts
      
    runs-on: ubuntu-latest
    services:
      irods:
        image: docker://wsinpg/ub-12.04-irods-4.1:latest
        ports:
          - 1247:1247

    container:
      image: docker://wsinpg/ub-12.04-conda:latest
#      volumes:
#        - ./conda_home:/home/conda

    steps:      
      - uses: actions/checkout@v1
      - name: debug
        run: |
          set -ex
          chmod g+w "$CONDA_INSTALL_DIR"
          
          useradd --shell /bin/bash --uid $CONDA_USER_ID --gid $CONDA_GROUP_ID --non-unique --create-home $CONDA_USER --comment ""
          cp "$CONDA_INSTALL_DIR/etc/condarc" "$CONDA_HOME/.condarc"
          chown -R $CONDA_USER:$CONDA_USER /home/$CONDA_USER
          
      - name: foo
        run: |
          set -ex
          export PATH="$CONDA_INSTALL_DIR/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          
          gosu $CONDA_USER /bin/bash
          ls $CONDA_INSTALL_DIR
          find $CONDA_INSTALL_DIR/etc
          env
          
#      - name: bar
#        run:
#          ls -l ./conda_home/*

  
        

