name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      irods:
        image: docker://wsinpg/ub-12.04-irods-4.1:latest
        ports:
          - 1247:1247

    container:
      image: docker://wsinpg/ub-12.04-conda:latest

    steps:      
      - uses: actions/checkout@v1
      - name: debug
        env:
         CONDA_USER_ID: 9001
         CONDA_USER: conda
         CONDA_GROUP_ID: 32001
         CONDA_INSTALL_DIR: /opt/conda
        run: |
          useradd --shell /bin/bash --uid $CONDA_USER_ID --gid $CONDA_GROUP_ID --non-unique --create-home $CONDA_USER --comment ""
          export USER=$CONDA_USER
          export HOME=/home/$USER
          export LOGNAME=$USER
          export MAIL=/var/spool/mail/$USER
          export PATH="$CONDA_INSTALL_DIR/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

          if [ ! -e "$HOME/.condarc" ]; then
            cp "$CONDA_INSTALL_DIR/etc/condarc" "$HOME/.condarc"
          fi

          chown -R $USER:$USER /home/$USER
          chmod g+w "$CONDA_INSTALL_DIR"

          exec gosu $USER whoami
          ls -l $HOME
          

